reset_cost:
  name: Reset cost
  description: Reset cost of sensor.
  target:
    entity:
      domain: sensor
calibrate:
  name: Calibrate
  description: Calibrate sensor.
  target:
    entity:
      domain: sensor
      integration: utility_meter
  fields:
    value:
      name: Value
      description: Set the sensor Value.
      required: true
      example: 100
      selector:
        number:
