#===============================================================================
# Home Assistant Main Configuration
# File: configuration.yaml
# Updated: 2025-08-22
# Note: Sensors moved to packages/integration_sensors.yaml
#===============================================================================

# Initial Config - Loads default set of integrations. Do not remove.
default_config:

#-------------------------------------------------------------------------------
# Text to speech default config
tts:
  - platform: google_translate  

#-------------------------------------------------------------------------------  
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#-------------------------------------------------------------------------------  
# HTTP Configuration
http:
  cors_allowed_origins:
    - "http://localhost"
    - "http://127.0.0.1"
    - "http://192.168.1.30"
  use_x_frame_options: false    

#-------------------------------------------------------------------------------
# Include Files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#-------------------------------------------------------------------------------
# Packages Configuration - Load all packages
homeassistant: 
  packages: !include_dir_named packages

#-------------------------------------------------------------------------------
# Shell Commands
shell_command:
  git_commit: '/config/scripts/git_commit.sh'
  export_sensor_list: >
    bash -c "hass-cli entity list | grep ^sensor."
  restart_deye_integration: >
    curl -X POST -H "Authorization: Bearer YOUR_TOKEN" \
    -H "Content-Type: application/json" \
    http://localhost:8123/api/config/config_entries/reload
  backup_config: >
    cp -r /config /backup/ha-config-$(date +%Y%m%d_%H%M%S)
  check_entity_status: >
    bash -c "hass-cli entity list | grep -E '(unknown|unavailable)'"

#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Recorder Configuration (Basic - Extended in packages)
recorder:
  # Keep 7 days of history for performance
  purge_keep_days: 7
  # Exclude some noisy entities
  exclude:
    domains:
      - automation
      - updater
      - camera
    entity_globs:
      - sensor.time*
      - sensor.date*
    entities:
      - sun.sun
      - weather.forecast_home

#-------------------------------------------------------------------------------
# Logger Configuration
logger:
  default: warning
  logs:
    # Monitor integration issues
    custom_components.deye_solar: info
    custom_components.localtuya: warning
    custom_components.battery_discovery: info
    homeassistant.components.mqtt: warning
    homeassistant.components.telegram_bot: info
    # Monitor entity issues
    homeassistant.helpers.entity: warning
    homeassistant.helpers.template: warning

#-------------------------------------------------------------------------------
# Energy Configuration
energy:
  # This will be configured via UI, but we document the key entities here
  # Grid consumption: sensor.total_grid_import
  # Grid return: sensor.total_grid_export  
  # Solar production: sensor.combined_solar_power
  # Battery storage: sensor.combined_battery_soc

#-------------------------------------------------------------------------------
# Comments for removed sections:
# - sensor: Moved to packages/integration_sensors.yaml
# - utility_meter: Moved to packages/integration_sensors.yaml
# - telegram_bot: Moved to packages/telegram_enhanced.yaml
# - template: Will be in various packages as needed