#Initial Config
# Loads default set of integrations. Do not remove.
default_config:
#-------------------------------------------------------------------------------
# Text to speech default config
tts:
  - platform: google_translate  
#-------------------------------------------------------------------------------  
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
#-------------------------------------------------------------------------------  
http:
  cors_allowed_origins:
    - "http://localhost"
    - "http://127.0.0.1"
    - "http://192.168.1.30"
  use_x_frame_options: false    
#-------------------------------------------------------------------------------
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# template: !include template.yaml    #we include template file here, soon replaced by packages folder
# template: !include template_MasterSlave_System.yaml  #change the config file depending on your system
#-------------------------------------------------------------------------------
# Sunsynk Inclusions
# Added on 7 Aug 2025 @ 13h16 by JB
homeassistant: 
  packages: !include_dir_named packages
#-------------------------------------------------------------------------------
# Sunsynk Inclusions
# Added on 7 Aug 2025 @ 13h16 by JB
# Telegram Bot config now in packages/telegram.yaml

# The sensor below keeps the minimum soc of the battery for the last 12 hours,
#only removed from DeyeSolarDesktop, not important
# sensor:
#   - platform: statistics
#     name: "min_soc_battery"
#     entity_id: sensor.deyeinverter_battery_soc
#     state_characteristic: value_min
#     max_age:
#       hours: 12
#     sampling_size: 144

sensor:
  - platform: integration
    name: deyeinvertermaster_summary_total_battery_charge_grid
    source: sensor.deyeinvertermaster_battery_charge_grid_power
    method: left

  - platform: integration
    name: deyeinverterslave_summary_total_battery_charge_grid
    source: sensor.deyeinverterslave_battery_charge_grid_power
    method: left

utility_meter:
  master_energy_battery_charge_grid:
    name: deyeinvertermaster_summary_day_battery_charge_grid
    source: sensor.deyeinvertermaster_summary_total_battery_charge_grid
    cycle: daily

  slave_energy_battery_charge_grid:
    name: deyeinverterslave_summary_day_battery_charge_grid
    source: sensor.deyeinverterslave_summary_total_battery_charge_grid
    cycle: daily
#-------------------------------------------------------------------------------      
# GitHub Commit Shell
# Added with Claude.ai on 20 Aug 2025
shell_command:
  git_commit: '/config/scripts/git_commit.sh'
  export_sensor_list: >
    bash -c "hass-cli entity list | grep ^sensor. > /config/sensor_list.txt"
#-------------------------------------------------------------------------------
# Security Logging
# Added with Claude.ai on 20 Aug 2025
logger:
  default: info
  logs:
    homeassistant.components.websocket_api: debug
    homeassistant.components.http.ban: warning
    custom_components: warning
    homeassistant.components.smtp: debug
    homeassistant.components.notify: debug
    homeassistant.components.automation: info
#-------------------------------------------------------------------------------
