

save:
  description: Сохраняет текущее состояние портов (?cmd=s)
  fields:

    mega_id:
      description: ID меги, можно оставить пустым, тогда будут сохранены все зарегистрированные меги
      example: "mega"

get_port:
  description: Запросить текущий статус порта (или всех)
  fields:
    mega_id:
      description: ID меги, можно оставить пустым, тогда будут сохранены все зарегистрированные меги
      example: "mega"
    port:
      description: Номер порта или список портов (если не заполнять, будут запрошены все порты сразу)
      example: 1

run_cmd:
  description: Выполнить любую произвольную команду
  fields:

    mega_id:
      description: ID меги, можно оставить пустым, тогда будут сохранены все зарегистрированные меги
      example: "mega"
    cmd:
      description: Любая поддерживаемая мегой команда
      example: "1:0"
    port:
      description: (Deprecated, больше не нужен) Номер порта (это не порт, которым мы управляем, а порт с которого шлем команду)
      example: 1

