# Security Monitoring Package
# Added with Claude.ai on 20 Aug 2025
# Created: {{ now().strftime('%Y-%m-%d') }}

# ==============================================================================
# SECURITY SENSORS
# ==============================================================================

binary_sensor:
  # Monitor for suspicious component activity
  - platform: template
    sensors:
      security_suspicious_activity:
        friendly_name: "Suspicious Security Activity"
        value_template: >
          {% set recent_logs = states('sensor.security_log_monitor') %}
          {{ 'config_editor' in recent_logs or 'directory_traversal' in recent_logs }}
        icon_template: >
          {% if is_state('binary_sensor.security_suspicious_activity', 'on') %}
            mdi:shield-alert
          {% else %}
            mdi:shield-check
          {% endif %}

      # Monitor failed login attempts
      security_failed_logins:
        friendly_name: "Failed Login Attempts Detected"
        value_template: >
          {% set recent_logs = states('sensor.security_log_monitor') %}
          {{ 'invalid authentication' in recent_logs.lower() or 'login attempt' in recent_logs.lower() }}

sensor:
  # System monitoring for security
# Removed on 20 Aug 2025 due to confligt  
#  - platform: systemmonitor
#    resources:
#      - type: network_in
#        arg: eth0
#      - type: network_out  
#        arg: eth0
#      - type: processor_use
#      - type: memory_use_percent

  # Command line sensor to monitor security logs
  - platform: command_line
    name: "Security Log Monitor"
    command: 'tail -100 /config/home-assistant.log | grep -E "(config_editor|websocket|invalid|failed|unauthorized|error)" | tail -10'
    scan_interval: 60  # Check every minute

  # Monitor WebSocket connections
  - platform: command_line
    name: "Active WebSocket Connections"
    command: 'grep "websocket" /config/home-assistant.log | tail -5'
    scan_interval: 300  # Check every 5 minutes

  # File modification monitor
  - platform: command_line
    name: "Recent File Changes"
    command: 'find /config -name "*.yaml" -mmin -60 | wc -l'
    scan_interval: 300
    unit_of_measurement: "files"



# ==============================================================================
# SECURITY DASHBOARD ELEMENTS
# ==============================================================================

input_boolean:
  security_monitoring_enabled:
    name: "Security Monitoring Active"
    icon: mdi:shield-check

  security_high_alert_mode:
    name: "High Alert Security Mode"
    icon: mdi:shield-alert

# For tracking security events
counter:
  security_failed_logins_count:
    name: "Failed Login Attempts Today"
    icon: mdi:account-alert
    step: 1

  security_suspicious_events_count:
    name: "Suspicious Events Today"  
    icon: mdi:alert-circle
    step: 1
#xxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxx